services:
  mysql:
    image: mysql:8.0
    container_name: my_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: poisepms
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  poise-pms:
    image: ijanvdwestz/poise-pms-app:latest
    container_name: poise_pms_container
    depends_on:
      - mysql
    environment:
      DB_URL: "jdbc:mysql://mysql:3306/poisepms"
      DB_USER: "root"
      DB_PASSWORD: "Jenice@18"
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true

volumes:
  mysql_data:
 